name: Generate Sitemap

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: "https://sbglobalventures.com"
          include-html: true 
          sitemap-path: "sitemap.xml"
          include-lastmod: true 

      - name: Commit sitemap
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sitemap.xml || true
          git add docs/sitemap.xml || true
          git commit -m "Auto-update sitemap" || echo "No changes to commit"
          git push
